### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JoeRoddy**
```
$ yarn start
yarn start v0.22.0
error Command "start" not found.
```

yarn run develop let me start the app.  Not sure if this is a change in yarn versions or what.

### CODE REVIEW

**Comment by alexvcasillas** [comment]
@JoeRoddy This is because there's no `yarn start` command on this project.
To run a development version you need to execute `yarn run develop`, because you're developing with it.

After you finish with the task of development you need to `yarn run pack` to pack and bundle everything into the `Electron` app or `yarn run pack:win` or your desired platform to pack and bundle for that specific environment.

I'm sorry the docs wheren't updated, this is a side project but I'll create specific documentation for this proyect today.

Thanks for the Pull Request : )

**Review by alexvcasillas — APPROVED** [review]
Approved the correction on the temporary documentation. Had this problem because of the inherited documents from #3RMXi 👍

**Comment by JoeRoddy** [comment]
Thanks for info Alex!

**Comment by alexvcasillas** [comment]
Thanks to you for the pull request @JoeRoddy.

I've also updated the Readme.md to be a little more specific with the commands while I work in the docs for this project :)

**Pull request merged**
